// ============================================================
//  data.js  —  Supply Chain Roadmap
//  Full 10-section roadmapData with rich topic content
//  Update topic details here; index.html reads this file
// ============================================================
const roadmapData = [
  {
    title: "Supply Chain Foundations",
    badge: "Start Here",
    content: {
      overview: `## What is it?\nSCM coordinates all activities involved in sourcing, procurement, production, and delivery of products — from raw materials to the end customer.\n\n## Why it matters\nA well-managed supply chain reduces costs, improves service levels, and creates competitive advantage.\n\n## Key Metrics / KPIs\n- Perfect Order Rate\n- Cash-to-Cash Cycle Time\n- OTIF (On Time In Full)\n- Inventory Turnover`,
      topics: {
        "What is Supply Chain Management": `## What is it?\nSCM coordinates the flow of goods, information, and money from raw materials to the end customer across a network of suppliers, manufacturers, and distributors.\n\n## Why it matters\nA well-run supply chain reduces costs, improves availability, and creates competitive advantage — Amazon and Walmart have built entire business models around supply chain excellence.\n\n## Key takeaway\nA great product with a poor supply chain will always lose to a good product with a great one.`,
        "Logistics & Distribution Basics": `## What is it?\nLogistics covers the planning, movement, and storage of goods — inbound from suppliers, internally between sites, and outbound to customers.\n\n## Why it matters\nLogistics typically represents 5–15% of a product's total cost, making it one of the highest-leverage levers for both profitability and customer service.\n\n## Key takeaway\nWithout reliable logistics, every upstream plan ultimately fails at the point of customer delivery.`,
        "Procurement & Sourcing Fundamentals": `## What is it?\nProcurement is the process of buying goods and services from external suppliers; sourcing is the strategic discipline of identifying, evaluating, and selecting the right suppliers for long-term value.\n\n## Why it matters\nProcurement spend typically represents 40–80% of a company's revenue, making supplier selection one of the most impactful financial levers in any business.\n\n## Key takeaway\nThe best procurement teams don't just negotiate the lowest price — they secure the right quality, reliability, and innovation.`,
        "Inventory Management Essentials": `## What is it?\nInventory management controls what stock to hold, how much, and where — balancing the cost of holding excess stock against the risk of running out and losing sales.\n\n## Why it matters\nInventory directly ties up working capital — every unit on the shelf is cash that could be deployed elsewhere.\n\n## Key takeaway\nZara holds just 6–8 days of stock vs the industry average of 52+ days — proof that inventory management is a source of competitive advantage.`,
        "Demand Planning Basics": `## What is it?\nDemand planning uses historical data, market intelligence, and commercial inputs to forecast future customer demand.\n\n## Why it matters\nA 10% improvement in forecast accuracy typically delivers 5–15% reduction in inventory and 2–3% improvement in service levels.\n\n## Key takeaway\nEvery supply chain decision downstream is only as good as the demand forecast it's built on.`,
        "Replenishment Planning Basics": `## What is it?\nReplenishment planning determines when to order more stock and how much — triggering purchase orders automatically when inventory falls to a calculated reorder point.\n\n## Why it matters\nPoor replenishment is the root cause of both stockouts (lost revenue) and overstock (wasted capital).\n\n## Key takeaway\nP&G's VMI programme with Walmart reduced Walmart's inventory by 30% while improving P&G's forecast accuracy by 40%.`,
        "Warehouse Operations Overview": `## What is it?\nWarehouse operations cover receiving, put-away, storage, picking, packing, and despatch — the physical engine room converting supply plans into customer deliveries.\n\n## Why it matters\nPick accuracy, throughput speed, and cost per order directly determine whether customer promises are kept.\n\n## Key takeaway\nAmazon's 750,000+ robots achieve 1.6M+ orders per day at 99.9% accuracy — proving warehouse design is a strategic, not just operational, decision.`,
        "Transportation Modes & Networks": `## What is it?\nTransportation modes — road, ocean, air, and rail — each offer different trade-offs of cost, speed, capacity, and carbon footprint.\n\n## Why it matters\nMode selection is one of the biggest cost levers — switching 10% of shipments from air to ocean can reduce freight cost on those lanes by up to 80%.\n\n## Key takeaway\nIKEA's flat-pack design triples container utilisation — turning packaging into a logistics cost reduction and sustainability strategy simultaneously.`,
        "Supply Chain KPIs (OTIF, Fill Rate, Inventory Turns)": `## What is it?\nSupply chain KPIs — OTIF, fill rate, inventory turns, and perfect order rate — track whether the supply chain is delivering on its service, cost, and efficiency commitments.\n\n## Why it matters\nWalmart penalises suppliers 3% of invoice value for missing 98.5% OTIF — making KPI performance a direct P&L issue.\n\n## Key takeaway\nWhat gets measured gets managed — the right KPI set aligns the entire supply chain organisation around the outcomes that matter.`
      }
    },
    items: ["What is Supply Chain Management","Logistics & Distribution Basics","Procurement & Sourcing Fundamentals","Inventory Management Essentials","Demand Planning Basics","Replenishment Planning Basics","Warehouse Operations Overview","Transportation Modes & Networks","Supply Chain KPIs (OTIF, Fill Rate, Inventory Turns)"]
  },
  {
    title: "Core Planning Processes",
    badge: "Core",
    content: {
      overview: `## What is it?\nCore planning processes are structured frameworks aligning supply with demand — from high-level S&OP down to day-to-day MRP execution.\n\n## Why it matters\nWithout structured planning, businesses react to problems instead of preventing them.\n\n## Key Metrics / KPIs\n- Forecast Accuracy\n- Plan Attainment %\n- Inventory vs Target DOS\n- Capacity Utilisation %`,
      topics: {
        "Plan → Source → Make → Deliver → Return": `## What is it?\nThe SCOR model defines five universal supply chain processes — Plan, Source, Make, Deliver, Return — providing a standard framework for describing, benchmarking, and improving any supply chain.\n\n## Why it matters\nCisco used SCOR after a $2.2B inventory write-down, cutting supply chain costs by $500M annually and improving OTIF from 70% to 95%.\n\n## Key takeaway\nSCOR gives every team a common language — turning vague improvement ambitions into specific, measurable process changes.`,
        "Sales & Operations Planning (S&OP)": `## What is it?\nS&OP is a monthly business planning process balancing demand, supply, inventory, and financial plans — producing one agreed operational plan.\n\n## Why it matters\nUnilever runs S&OP across 190 countries, resolving supply gaps 8 weeks before they become customer service failures.\n\n## Key takeaway\nS&OP replaces reactive firefighting with proactive decision-making — it is the heartbeat of a well-run supply chain.`,
        "Integrated Business Planning (IBP)": `## What is it?\nIBP extends S&OP by fully integrating financial planning, strategic initiatives, and portfolio management.\n\n## Why it matters\nGSK implemented IBP across 47 manufacturing sites, reducing working capital by £400M and improving forecast accuracy from 60% to 85% MAPE.\n\n## Key takeaway\nIBP elevates supply chain planning from an operational activity to a strategic business process that drives financial performance.`,
        "Master Production Scheduling (MPS)": `## What is it?\nThe MPS specifies exactly what to produce, in what quantities, and when — translating the S&OP into a feasible production programme.\n\n## Why it matters\nBoeing's MPS coordinates 367 major suppliers and 600,000+ parts — today's schedule drives purchase orders for components assembled six months later.\n\n## Key takeaway\nThe MPS is the bridge between commercial ambition and manufacturing reality.`,
        "Material Requirements Planning (MRP)": `## What is it?\nMRP calculates what materials are needed, in what quantities, and when — by exploding the production schedule through the Bill of Materials.\n\n## Why it matters\nToyota's MRP system is so precise that components arrive at the assembly line within a 2-hour window — eliminating on-site warehousing and saving billions.\n\n## Key takeaway\nMRP is the engine that translates a sales plan into purchase orders.`,
        "Capacity Planning": `## What is it?\nCapacity planning ensures manufacturing, warehousing, and logistics resources are sufficient to meet the production plan — identifying bottlenecks before they cause missed deliveries.\n\n## Why it matters\nDuring the 2021 chip shortage, TSMC's capacity allocation decisions determined which entire industries could build products.\n\n## Key takeaway\nCapacity planning is the reality check of supply chain — where optimistic sales plans meet hard constraints.`,
        "Order Management & Fulfillment": `## What is it?\nOrder management covers the end-to-end process from receiving a customer order to delivery.\n\n## Why it matters\nAmazon processes 1.6M+ orders per day with 99.9%+ accuracy, automatically selecting the optimal fulfilment centre, carrier, and route for each order.\n\n## Key takeaway\nOrder management is where supply chain performance becomes visible to the customer.`,
        "Supplier Relationship Management": `## What is it?\nSRM is the systematic approach to segmenting, evaluating, developing, and managing suppliers — going beyond transactional purchasing to strategic partnership.\n\n## Why it matters\nApple's SRM team works with TSMC 3–5 years ahead of product launches, pre-paying billions in capacity.\n\n## Key takeaway\nThe best supply chains treat key suppliers as an extension of their own organisation.`
      }
    },
    items: ["Plan → Source → Make → Deliver → Return","Sales & Operations Planning (S&OP)","Integrated Business Planning (IBP)","Master Production Scheduling (MPS)","Material Requirements Planning (MRP)","Capacity Planning","Order Management & Fulfillment","Supplier Relationship Management"]
  }
  // ⬇ Sections 3–10 follow exactly the same structure.
  // Paste the remaining 8 sections from your original data.js here.
  // Each section uses: { title, badge, content: { overview, topics: { "Topic Name": "content..." } }, items: [...] }
];
